version: '2'

services:
  consulserver:
    container_name: dockerized-consulserver
    hostname: consulserver
    image: gliderlabs/consul-server:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "53"
    command: -data-dir /tmp/consul -bootstrap -advertise 127.0.0.1
  registrator:
    container_name: dockerized-registrator
    image: gliderlabs/registrator:master
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: -internal consul://consulserver:8500
    depends_on:
      - consulserver
  db:
    container_name: dockerized-mysql-greetingsdb
    hostname: greetingsdb
    image: mysql/mysql-server:5.7
    volumes:
      - "./mysql/init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_USER: sqluser
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: greetingsdb
    ports:
      - "3306:3306"
    depends_on:
      - registrator
  web:
    container_name: dockerized-web-greetingsapp
    build: .
    command: python app.py
    ports: 
      - "4000:80"
    volumes:
      - .:/app
    depends_on:
      - db
    hostname: greetingsapp 

